name: Run tests on merge to master

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v2
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B clean test
